for _, lab in pairs(data.raw["lab"]) do
    table.insert(lab.inputs, "sero-manufacturing-science-pack")
    table.insert(lab.inputs, "sero-industry-science-pack")
    table.insert(lab.inputs, "sero-upkeep-science-pack")
    table.insert(lab.inputs, "sero-control-science-pack")
    table.insert(lab.inputs, "sero-execution-science-pack")
    table.insert(lab.inputs, "sero-system-science-pack")
    table.insert(lab.inputs, "sero-ammunition-science-pack")
    table.insert(lab.inputs, "sero-expansion-science-pack")
    table.insert(lab.inputs, "sero-precision-science-pack")
    table.insert(lab.inputs, "sero-instrumentation-science-pack")
    table.insert(lab.inputs, "sero-hazardous-science-pack")
    table.insert(lab.inputs, "sero-composites-science-pack")
    table.insert(lab.inputs, "sero-electromagnetic-science-pack")
    table.insert(lab.inputs, "sero-dynamics-science-pack")
    table.insert(lab.inputs, "sero-expulsion-science-pack")
    table.insert(lab.inputs, "sero-complication-science-pack")
    table.insert(lab.inputs, "sero-communication-science-pack")
    table.insert(lab.inputs, "sero-offense-science-pack")
    table.insert(lab.inputs, "sero-fabrication-science-pack")
    table.insert(lab.inputs, "sero-physics-science-pack")
end
